[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Các test case quan trọng kiểm tra chức năng cốt lõi (Smoke Test)
    regression: Bộ kiểm thử hồi quy (Regression Test)
    login: Các test case kiểm tra chức năng Đăng nhập
    inventory: Các test case kiểm tra chức năng Trang sản phẩm
    edge: Các test case kiểm tra đóng mở và tương tác trên trình duyệt Microsoft Edge

addopts = 
    -v
    -s
    --html=reports/test_report.html
    --self-contained-html

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
